### ISSUE TITLE
Connector expects port inside Node URL

### ISSUE THREAD

**Issue by penumbra23** [Analog-Labs/chain-connectors#149]
**Description**

Assigning a node RPC URL without the port gives the following error:

`No port number in URL (default port is not supported)`.

**Expected behavior**:

Connector should be fine to assume default ports for HTTPS or WSS (443).

**Comment by Lohann** [comment]
The issue is parity's [subxt](https://github.com/paritytech/subxt) that requires a explicit port, I'll do this change.

**Comment by Lohann** [comment]
I've created a new issue that is related to this one, the port is not the real issue, the HTTP version is:
https://github.com/Analog-Labs/chain-connectors/issues/151
