### ISSUE TITLE
Human Node Chain Integration

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#238]
**Feature description**
Human Node Chain Integration

- [x] Integration on chain-connector
- [ ] Update on timechain
- [x] local humanode setup for testing
- [ ] Unit testing
- [ ] CI setup

**Tests instructions**

- Unit tests
- Integration tests

**References Material**

- Technical Specs
- Related docs
- Example code

**Comment by ManojJiSharma** [comment]
https://github.com/Analog-Labs/chain-connectors/issues/259
